In [54]:
import pandas as pd

In [55]:
dfData = pd.read_csv('./Datasets/DatosProcesados.csv')

In [56]:
dfData

      Gender  Age  ...  MTRANS_Public_Transportation  MTRANS_Walking
0     Female   21  ...                          True           False
1     Female   21  ...                          True           False
2       Male   23  ...                          True           False
3       Male   27  ...                         False            True
4       Male   22  ...                          True           False
...      ...  ...  ...                           ...             ...
2106  Female   20  ...                          True           False
2107  Female   21  ...                          True           False
2108  Female   22  ...                          True           False
2109  Female   24  ...                          True           False
2110  Female   23  ...                          True           False

[2111 rows x 24 columns]

In [57]:
dfData = pd.get_dummies(dfData, columns=['CAEC', 'CALC', 'MTRANS'], drop_first=True)

In [58]:
dfData.head(10)

   Gender  Age  ...  MTRANS_Public_Transportation  MTRANS_Walking
0  Female   21  ...                          True           False
1  Female   21  ...                          True           False
2    Male   23  ...                          True           False
3    Male   27  ...                         False            True
4    Male   22  ...                          True           False
5    Male   29  ...                         False           False
6  Female   23  ...                         False           False
7    Male   22  ...                          True           False
8    Male   24  ...                          True           False
9    Male   22  ...                          True           False

[10 rows x 24 columns]

In [59]:
dfData = pd.get_dummies(dfData, columns=['Gender'], drop_first=True)

In [60]:
dfData.to_csv('./Datasets/DatosProcesados.csv', index=False)